---

- hosts: all
  become: true
  tasks:
 
  - name: Install apache2 and php package and Update cache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Start apache2
    service:
      name: apache2
      state: started
